# Generated by Django 5.1.6 on 2025-03-01 16:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0002_alter_posts_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
