# Generated by Django 5.1.6 on 2025-03-01 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0003_alter_posts_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('post_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_app.posts')),
            ],
        ),
    ]
